name: Build and Publish Docs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'env_loader/**'
jobs:
  build-and-deploy-docs:
    name: Build and publish docs
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.9
      - name: Install dependencies
        run: python3 -m pip install sphinx sphinx-rtd-theme autodocsumm
      - name: Build docs
        run: cd docs && make html && cd .. && mv docs/_build/html generated-docs && rm -rf docs
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: main # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: generated-docs # The folder the action should deploy.
